spring:
  application:
    name: sistema-encuestas

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  server:
    port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

brevo:
  api-key: ${BREVO_API_KEY}
  from: ${BREVO_FROM:notificaciones.sondevia@gmail.com}
