spring:
  application:
    name: sistema-encuestas

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 465
    username: notificaciones.sondevia@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  server:
    port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
